### ISSUE TITLE
IceTransport ConcurrentModificationException

### ISSUE THREAD

**Issue by bkempe** [jitsi/jitsi-videobridge#1017]
## Description

Seeing a `ConcurrentModificationException` on ice4j's `Component` in the latest JVB code. It  seems that `IceTransport` accesses the same `Component` on multiple threads and therefore locks might be needed.
```
java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at org.ice4j.ice.Component.findRemoteCandidate(Component.java:931)
	at org.jitsi.videobridge.IceTransport.addRemoteCandidates(IceTransport.java:541)
	at org.jitsi.videobridge.IceTransport.startConnectivityEstablishment(IceTransport.java:449)
	at org.jitsi.videobridge.DtlsTransport.startConnectivityEstablishment(DtlsTransport.java:217)
	at org.jitsi.videobridge.Endpoint.setTransportInfo(Endpoint.java:1073)
	at org.jitsi.videobridge.shim.VideobridgeShim.handleColibriConferenceIQ(VideobridgeShim.java:430)
	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:608)
	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:593)
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQRequest(XmppCommon.java:202)
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQInternal(XmppCommon.java:158)
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQ(XmppCommon.java:129)
	at org.jitsi.videobridge.xmpp.ClientConnectionImpl.handleIq(ClientConnectionImpl.java:112)
	at org.jitsi.xmpp.mucclient.IQListener.handleIq(IQListener.java:50)
	at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:446)
	at org.jitsi.xmpp.mucclient.MucClient.access$500(MucClient.java:47)
	at org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:412)
	at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

# Environment details
---
Latest JVB on commit hash e7d4a727b32b039e54abd676cd03df1c37a68642

**Comment by nightvisi0n** [comment]
I also experienced this on `stable-5390-3` after triggering shutdown via the API.  

```
Exception in thread "main" java.util.ConcurrentModificationException
        at java.util.Hashtable$Enumerator.next(Hashtable.java:1387)
        at org.jitsi.videobridge.MainKt.stopIce4j(Main.kt:241)
        at org.jitsi.videobridge.MainKt.main(Main.kt:175)
```

**Comment by bgrozev** [comment]
Thanks for reporting, fixed in #1594
