### ISSUE TITLE
com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize()

### ISSUE THREAD

**Issue by grinapo** [jitsi/jitsi-videobridge#1127]
## Description
Stats doesn't work.

```
JVB 2020-03-17 19:28:58.126 SEVERE: [26] org.jitsi.utils.concurrent.RecurringRunnableExecutor.log() The invocation of the method org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.run() threw an exception.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @1654fa08
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at org.jitsi.videobridge.stats.OsStatistics.getTotalMemory(OsStatistics.java:138)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate0(VideobridgeStatistics.java:703)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate(VideobridgeStatistics.java:450)
        at org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.doRun(StatsManager.java:321)
        at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

```

## Possible Solution
[StackOverflow](https://stackoverflow.com/questions/55952859/unable-to-make-public-long-com-sun-management-internal-operatingsystemimpl-getop) wisdom says: *One of the dependencies of your project is trying to access a jvm api which was moved to an internal java module, and is no longer exposed.*

# Environment details
openjdk-11 (as suggested by the debian package, and anyway).

**Comment by damencho** [comment]
Probably using java8 will fix it. Also, it is good to report which version of jvb you are using.  I think this stat was removed from the latest jvb anyway.

**Comment by grinapo** [comment]
And *downgrading by 3 major versions* doesn't negatively impact performance or stability? 
(Apart from the fact that there is no java8 in Debian/buster.)

**Comment by damencho** [comment]
This is the current recommended version to run everything, including that jvb2 is fine tuned to work with it (the garbage collection...).

**Comment by hex-m** [comment]
I used the [quick install manual](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) and got to the same problem (on Debian 10). The jitsi-videobridge package depends on openjdk-8-jre-headless OR openjdk-11-jre-headless and defaults to version 11 on my system.
If Java 11 is not supported I would consider this a bug in the Debian package.

**Comment by CyrilBrulebois** [comment]
It doesn't seem to be too wise to tell people to stick to old Java versions.

Anyway, looking around, I've noticed the following workaround in this Jenkins issue: https://issues.jenkins-ci.org/browse/JENKINS-52017

Adding `--add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED` to `JAVA_SYS_PROPS` in `/etc/jitsi/videobridge/config` and restarting the daemons made the Java stacktraces go away, and I'm seeing meaningful statistics now.

This seems to be a heavy hammer (one could probably spot the right bits that need to be listed there instead of this catch-all), but maybe that'll do the job for some users until a proper solution is found.

**Comment by damencho** [comment]
This is how we run it, and how we tweaked it, we made it at least run on java11 (as at some point it wasn't starting on java11 and would not install with java11). In the future, we will tweak it and for it and will drop java8, but we are still not there. Considering the current crazy times this is low priority at the moment. We will soon release jvb2 and any way that stat is not there, I think.

**Comment by grinapo** [comment]
What about, um, dropping the stat and make it work on something not from 2014? Am I being naïve here?

**Comment by damencho** [comment]
This will come with bridge 2.0. We no longer do modifications to jvb1, if we do, it will not hit stable anyway ... so you can just try running jvb2. If that is a problem there we can fix it there. But even jvb2 is tweaked for java8 gc to perform better.

**Comment by damencho** [comment]
You are free to rebuild it with modifications, to make it run your way.

**Comment by paulmenzel** [comment]
Just for the record, this also happens with the nightly package jitsi-videobridge 1132-1 from `unstable/`.

    deb https://download.jitsi.org unstable/

**Comment by damencho** [comment]
We are not doing any changes to jitsi-videobridge, try jitsi-videobridge2.

**Comment by paulmenzel** [comment]
Also, OpenJDK 8 is not available in Debian 10 Buster/stable anymore: https://packages.debian.org/search?keywords=openjdk-8.

**Comment by paulmenzel** [comment]
Trying to install `jitsi-videobridge2` from the unstable archive, APT wants to remove `jitsi-meet`: https://github.com/jitsi/jitsi-videobridge/issues/1139.

**Comment by damencho** [comment]
https://community.jitsi.org/t/jvb-2-considered-stable/24314/7?u=damencho

**Comment by Mebus** [comment]
Hallo,

this also happens with `jitsi-videobridge2              2.1-180-g03b2fc4b-1` on Debian 10:

```
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @12db7337
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at org.jitsi.videobridge.stats.OsStatistics.getTotalMemory(OsStatistics.java:138)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate0(VideobridgeStatistics.java:703)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate(VideobridgeStatistics.java:450)
        at org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.doRun(StatsManager.java:321)
        at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```
Mebus

**Comment by nemobis** [comment]
Confirmed also with 2.1-203:
```
JVB 2020-05-24 09:50:29.354 GRAVE: [27] org.jitsi.utils.concurrent.RecurringRunnableExecutor.log() The invocation of the method org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.run()
threw an exception.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @2f6d71e1
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at org.jitsi.videobridge.stats.OsStatistics.getTotalMemory(OsStatistics.java:138)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate0(VideobridgeStatistics.java:703)
        at org.jitsi.videobridge.stats.VideobridgeStatistics.generate(VideobridgeStatistics.java:450)
        at org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.doRun(StatsManager.java:321)
        at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```

Versions:
```
# dpkg -l | grep jitsi
ii  jitsi                           2.11.5624-1                     amd64        VoIP and Instant Messaging client
ii  jitsi-archive-keyring           1.0.1                           all          The public key for the Jitsi packages repository
ii  jitsi-meet                      2.0.4642-1                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.4139-1                      all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.4139-1                      all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.4139-1                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.4139-1                      all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.1-203-g83195fcd-1             all          WebRTC compatible Selective Forwarding Unit (SFU)
# dpkg -l | grep jdk
ii  openjdk-11-jre:amd64            11.0.7+10-3~deb10u1             amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64   11.0.7+10-3~deb10u1             amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```
