### ISSUE TITLE
Failed to bind single-port

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-videobridge#1142]
Using jitsi-videobridge2 2.1-149-g88cd7e1b-1, the log is spammed with exceptions, that it failed to bind a single port.

https://github.com/jitsi/jitsi-videobridge/blob/88cd7e1b3f9d138b9c1b21300ee46abc80fa5c61/src/main/java/org/jitsi/videobridge/health/Health.java#L143

**Comment by bbaldino** [comment]
Can you give a bit more information?  How do you have it configured?  Where is this running? Which port is it set up for? Did you check if something else was using it?

**Comment by paulmenzel** [comment]
I did `apt purge jitsi-videobridge` and then `apt install jitsi-videobridge2`. Rebooted the system, and there were problems accessing Jitsi Meet (Web site). This is what I found in the JVB logs.

I didn’t change anything. How do I find out, what port it tried to bind to? (Maybe, the log message could be extended to contain that information?)

**Comment by bbaldino** [comment]
Can you attach logs?

**Comment by pshunter** [comment]
Hi, I also had this in jitsi-videobridge when a port range was specified in /etc/jitsi/vidobridge/config (JVB_OPTS="--min-port=xxxx --max-port=yyyy") and the port from /etc/jitsi/vidobridge/sip-communicator.properties org.jisti.videobridge.SINGLE_PORT_HARVESTER_PORT=zzzz fell in that range. It seems that it steps on it own feet while trying to bind the same port twice.

**Comment by bgrozev** [comment]
> I didn’t change anything. How do I find out, what port it tried to bind to? (Maybe, the log message could be extended to contain that information?)

You can see this early in the logs (it tries to bind once on startup, on failure it just repeats the exception). Look for 'SinglePortUdpHarvester' or 'Harvesters'.



> It seems that it steps on it own feet while trying to bind the same port twice.

This shouldn't happen at all with jvb 2, it doesn't use a port range.

**Comment by pshunter** [comment]
> This shouldn't happen at all with jvb 2, it doesn't use a port range.
You are right, I had that error in jvb 1. So this rules out that cause, I suppose

**Comment by paulmenzel** [comment]
I took another stab, updating from *jitsi-videobridge* 1132-1 to *jitsi-videobridge2* 2.1-209-g2d8a2fcf-1, and I am still getting the error.

The package update changed `/etc/jitsi/videobridge/sip-communicator.properties`:

```
@@ -7,3 +7,5 @@ org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
 org.jitsi.videobridge.xmpp.user.shard.PASSWORD=OlDZNv9t
 org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.jitsi.molgen.mpg.de
 org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=63b640cb-e1ed-4260-812f-15aca588faa2
+org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
+org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
```

The file now looks like below:

```
org.jitsi.videobridge.DISABLE_TCP_HARVESTER=true
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.jitsi.molgen.mpg.de
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=[XXXXXX]
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.jitsi.molgen.mpg.de
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=[obfuscated]
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
```
There are no port range settings:

```
$ grep JVB_OPTS /etc/jitsi/videobridge/config
JVB_OPTS="--apis=,"
```

Here is one error message:

```
[…]
2020-05-28 10:44:55.950 INFO: [22] AbstractHealthCheckService.run#182: Performed a successful health check in PT0.002087S. Sticky failure: false
2020-05-28 10:45:04.029 INFO: [21] Videobridge.createConference#290: create_conf, id=c6ac4e75b69ec2f5 gid=null logging=false
2020-05-28 10:45:04.042 INFO: [21] TaskPools.<clinit>#81: TaskPools detected 12 processors, creating the CPU pool with that many threads
2020-05-28 10:45:04.132 INFO: [21] org.ice4j.ice.harvest.SinglePortUdpHarvester.createHarvesters: Failed to create SinglePortUdpHarvester for address 141.14.220.179:10000/udp: java.net.BindException: Address already in use (Bind failed)
141.14.220.179:10000/udp: java.net.BindException: Address already in use (Bind failed)
2020-05-28 10:45:04.132 INFO: [21] Harvesters.initializeStaticConfiguration#90: No single-port harvesters created.
2020-05-28 10:45:04.140 WARNING: [21] [confId=c6ac4e75b69ec2f5 epId=74ef2f8e local_ufrag=c8use1e9d79jnt ufrag=c8use1e9d79jnt] Agent.gatherCandidates#6
74: No host harvesters available!
2020-05-28 10:45:04.140 WARNING: [21] [confId=c6ac4e75b69ec2f5 epId=74ef2f8e local_ufrag=c8use1e9d79jnt ufrag=c8use1e9d79jnt] Agent.gatherCandidates#6
83: Failed to gather any host candidates!
SCTP JNI load: Linux OS detected
SCTP lib loaded
=====>: org_jitsi_modified_sctp4j_SctpJni.c calling init
=====>: org_jitsi_modified_sctp4j_SctpJni.c about to set SCTP_DEBUG_ALL
2020-05-28 10:45:04.880 WARNING: [21] [confId=c6ac4e75b69ec2f5 epId=4b65a034 local_ufrag=fgl3t1e9d79kff ufrag=fgl3t1e9d79kff] Agent.gatherCandidates#6
74: No host harvesters available!
2020-05-28 10:45:04.880 WARNING: [21] [confId=c6ac4e75b69ec2f5 epId=4b65a034 local_ufrag=fgl3t1e9d79kff ufrag=fgl3t1e9d79kff] Agent.gatherCandidates#6
83: Failed to gather any host candidates!
2020-05-28 10:45:04.889 INFO: [21] AbstractHealthCheckService.run#182: Performed a successful health check in PT0.872694S. Sticky failure: false
2020-05-28 10:45:05.948 INFO: [22] Videobridge.createConference#290: create_conf, id=72fbcf66783ed3e9 gid=null logging=false
2020-05-28 10:45:05.950 INFO: [22] AbstractHealthCheckService.run#182: Performed a successful health check in PT0.002307S. Sticky failure: false
2020-05-28 10:45:14.017 SEVERE: [21] AbstractHealthCheckService.run#185: Health check failed in PT0.000076S:
java.lang.Exception: Failed to bind single-port
        at org.jitsi.videobridge.health.Health.performCheck(Health.java:161)
        at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:155)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
2020-05-28 10:45:15.948 INFO: [22] Videobridge.createConference#290: create_conf, id=e1a3129ad311bea0 gid=null logging=false
2020-05-28 10:45:15.950 INFO: [22] AbstractHealthCheckService.run#182: Performed a successful health check in PT0.001952S. Sticky failure: false
[…]
```

So it’s port 10000, and it seems to be the JVB “owning” it:

    $ sudo lsof -iUDP -P -n | grep 10000
    java        355        jvb  135u  IPv6   9567      0t0  UDP 141.14.220.179:10000 
    $ ps -aux -q355
    USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    jvb        355  0.3  5.0 10266904 409680 ?     Ssl  May27   5:16 java -Xmx3072m -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPa
th=/tmp -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicat
or.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties --add-opens jdk.management/com.sun.man
agement.internal=ALL-UNNAMED -cp /usr/share/jitsi-videobridge/jitsi-videobridge.jar:/usr/share/jitsi-videobridge/lib/* org.jitsi.videobridge.Main --ho
st= --domain=jitsi.molgen.mpg.de --port=5347 --apis=,

**Comment by bgrozev** [comment]
> 141.14.220.179:10000/udp: java.net.BindException: Address already in use (Bind failed)

You have another process (probably another jvb process) already running and using that port.

**Comment by paulmenzel** [comment]
> > 141.14.220.179:10000/udp: java.net.BindException: Address already in use (Bind failed)
> 
> You have another process (probably another jvb process) already running and using that port.

@bgrozev, spot on. I still had the service unit `/etc/systemd/system/jitsi-videobridge.service`, which I had added to get rid of the shell wrapper script. Thank you.
