### ISSUE TITLE
JDK 11 compatibility

### ISSUE THREAD

**Issue by xranby** [jitsi/jitsi-videobridge#1149]
## Description
When using java 11 JAXB is no longer part of the jdk.
 Motivation why it was removed: http://openjdk.java.net/jeps/320
This is the root cause why jitsi-videobridge and jicofo do not work with JDK 11
---
## Current behavior
Users are unable to use the videobridge on systems using openjdk 11
Users see "oops something went wrong" and the browser reload endlessly

The JVB log throws an exception
java.lang.NoClassDefFoundError: javax/xml/bind/Unmarshaller
---

## Possible Solution
The solution is to include the official jaxb jars from javaee 
when jitsi-videobridge and jicofo are compiled!
 https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#deployment-maven-coordinates
This is the dependency from maven central that needs to be added to the video bridge and jicofo build:

    <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.1</version>
    </dependency>

**Comment by xranby** [comment]
Ping: @JonathanLennox

**Comment by JonathanLennox** [comment]
Can you send the stack of the exception?  I believe these dependencies come from the Jersey library, so a better fix will be to update the version of Jersey to one with JDK11-compatibility.

The PR https://github.com/jitsi/jitsi-videobridge/pull/1136 does that (and some other JDK11-related fixes), so can you see if that fixes the problem for you?

**Comment by xranby** [comment]
Stack trace: jaxb dependency indeed originate from Jersey.

I will try compile  JVB with PR #1136 applied and report back.
Is there a similar PR for Jicofo? 

Both JVB and Jicofo depend on Jersey.

The stack trace actually comes from Jicofo. Since that component triggers this bug first on my system. sorry for filing the bug against the wrong component. :)
```
Jicofo 2020-03-22 17:08:33.318 VARNING: [12] org.glassfish.jersey.internal.Errors.logErrors() The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.
internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1354)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1350)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1350)
        at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1293)
        at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:60)
        at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:124)
        at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:156)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:105)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:156)
        at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:716)
        at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:670)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:441)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2287)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:105)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1372)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1367)
        at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:105)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1429)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1355)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1343)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:134)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
        at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:307)
        at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:218)
        at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:113)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:349)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:349)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:428)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:415)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:607)
        at org.jitsi.jicofo.auth.AuthBundleActivator.start(AuthBundleActivator.java:233)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 73 more
```

**Comment by damencho** [comment]
We did fix some of those in latest unstable packages. Can you check those do they work for you, as very very soon those will be stable.

**Comment by xranby** [comment]
@damencho @JonathanLennox the latest unstable jitsi-meet packages _work_ on debian with java 11. Thank you! closing
