### ISSUE TITLE
Could not instanciate a conference: java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by jeanpalaz** [jitsi/jitsi-videobridge#1177]
## Description
---
Hi, 
I have installed Jitsi on my raspberry pi 3 , and want to create a meeting in my LAN 

## Current behavior
---
message: 
"Unfortunatly something went wrong
We are trying to fix this ..."

## Expected Behavior
---
Use meeting !

## Possible Solution
---
?

# Environment details
---
Raspberri PI 3 / Raspbian 9.11

After a VM error
```
Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
```
 I have put `VIDEOBRIDGE_MAX_MEMORY=1024m` in `/etc/jitsi/videobridge/config`
Restart service videobridge
But now I have a 

```
2020-04-07 12:06:04.977 INFOS: [15] VideobridgeExpireThread.expire#144: Running expire()
2020-04-07 12:06:08.957 INFOS: [16] Videobridge.createConference#326: create_conf, id=a8ca0ddfb571edbb gid=null logging=false
2020-04-07 12:06:08.996 GRAVE: [16] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.videobridge.sctp.SctpManager
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:709)
	at org.jitsi.videobridge.health.Health.check(Health.java:93)
	at org.jitsi.videobridge.health.Health.doCheck(Health.java:161)
	at org.jitsi.videobridge.health.Health.doRun(Health.java:266)
	at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

```

Thank you for helping !
Jean

**Comment by jeanpalaz** [comment]
I have found this in logs:
```
2020-04-07 12:04:08.512 INFOS: [21] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-07 12:04:08.857 INFOS: [21] [hostname=localhost id=shard] MucClient$MucWrapper.join#751: Joined MUC: jvbbrewery@internal.auth.192.168.1.22
SCTP JNI load: Linux OS detected
OpenJDK Client VM warning: You have loaded library /tmp/nativeutils7853908189650239/libjnisctp.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
2020-04-07 12:04:10.873 GRAVE: [16] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.UnsatisfiedLinkError: /tmp/nativeutils7853908189650239/libjnisctp.so: /tmp/nativeutils7853908189650239/libjnisctp.so: mauvaise classe ELF : ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:109)
	at org.jitsi_modified.sctp4j.SctpJni.<clinit>(SctpJni.java:31)
	at org.jitsi_modified.sctp4j.Sctp4j.init(Sctp4j.java:40)
	at org.jitsi.videobridge.sctp.SctpManager.<clinit>(SctpManager.java:54)
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:709)
	at org.jitsi.videobridge.health.Health.check(Health.java:93)
	at org.jitsi.videobridge.health.Health.doCheck(Health.java:161)
	at org.jitsi.videobridge.health.Health.doRun(Health.java:266)
	at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
2020-04-07 12:04:20.876 INFOS: [16] Videobridge.createConference#326: create_conf, id=3308bfe1484ceba3 gid=null logging=false
2020-04-07 12:04:22.474 GRAVE: [16] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.videobridge.sctp.SctpManager
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:709)

```
I hope that it can help ..

Thank you

**Comment by JonathanLennox** [comment]
Data channels will not currently work on arm-based platforms, because the SCTP implementation depends on native code.

Fortunately, you can configure jitsi-meet to use Websockets instead, by setting 

```
openBridgeChannel: 'websocket', // One of true, 'datachannel', or 'websocket'
```

which will be fully supported.

**Comment by jeanpalaz** [comment]
tried it on /etc/jitsi/meet/192.168.1.2-config.js 
and I still have the problem reload service (and reboot to be sure...)
:(
