### ISSUE TITLE
Packaged release is too old to support current jicofo

### ISSUE THREAD

**Issue by C0rn3j** [jitsi/jitsi-videobridge#1224]
I think it's [this commit](https://github.com/jitsi/jicofo/commit/ec1b29ed5b4b11848d5f29422bc73c08822c82b4) from a few days ago that broke the currently (very old) packaged videobridge on
https://download.jitsi.org/jitsi-videobridge/linux/

Jicofo will fail the health check on the bridge and JM won't run properly:
```
Jicofo 2020-04-25 10:09:56.623 SEVERE: [30] org.jitsi.jicofo.health.Health.log() Health check failed in PT0.005S:
java.lang.RuntimeException: No operational bridges available (total bridge count: 0)
        at org.jitsi.jicofo.health.Health.check(Health.java:127)
        at org.jitsi.jicofo.health.Health.performCheck(Health.java:89)
        at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```

I guess this is because the healthcheck that jicofo is looking for was added sometime after January, which is the date of the current package.

I compiled the git version of jitsi-videobridge and jicofo picked it up and things started working again.

EDIT: Guess Github releases should be used now?
https://github.com/jitsi/jitsi-videobridge/releases

**Comment by jvkassi** [comment]
Hello,
What is the workaround?

**Comment by C0rn3j** [comment]
Not using the old JVB.

**Comment by jvkassi** [comment]
We are using those versions
jicofo_1.0-612-1  (latest release)
jvb 2.1-273 (latest release)

**Comment by C0rn3j** [comment]
Then you're not running into this problem

**Comment by jvkassi** [comment]
Please, I have the same error:
 
```
Jicofo 2020-08-28 17:59:38.016 GRAVE: [39] org.jitsi.jicofo.health.Health.log() Health check failed in PT0S:
java.lang.RuntimeException: No operational bridges available (total bridge count: 0)
        at org.jitsi.jicofo.health.Health.check(Health.java:183)
        at org.jitsi.jicofo.health.Health.performCheck(Health.java:133)
        at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:155)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```


This is my configuration of jicofo

/etc/jitsi/jicofo/sip-communicator.properties

```
org.jitsi.jicofo.health.ENABLE_HEALTH_CHECKS=true

/etc/jitsi/jicofo/config
````
# extra options to pass to the jicofo daemon
JICOFO_OPTS='--apis=rest,xmpp'
```

```
ii  jicofo                              1.0-612-1                                  all          JItsi Meet COnference FOcus
ii  jitsi-videobridge2                  2.1-273-g072dd44b-1                        all          WebRTC compatible Selective Forwarding Unit (SFU)
```

Do you i have to do some configuration on JVB too ?
