### ISSUE TITLE
Unexpected Error when joining videobridge meeting

### ISSUE THREAD

**Issue by hiddehs** [jitsi/jitsi-videobridge#1243]
## Description
Jitsi Meet is overall working correctly, but once every ~5 joins something goes wrong. 
When joining a videobridge meeting (>2 participants) the person that joins experiences a connection loss, while the new participant can see the list of the other participants in the group meeting by name, there is no sound/video connection being made (from the participant to the others and vice versa).

The videobridge log (`/var/log/jitsi/jvb.log`) shows an unexpected error at the moment of faulty joining (`2020-05-04 11:19:53.573 SEVERE: [117]`). 
When the new participant tries to join again it sometimes happens again, but most of the times the joining procedure is completed successfully the second time and the participant is connected correctly to the group meeting.

```
2020-05-04 11:19:53.572 INFO: [117] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE componentId=1 conf_name=standup ufrag=ct91h1e7ffo1f8 name=stream-d02203e7 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] ComponentSocket.addAuthorizedAddress#99: Adding allowed address: 89.205.129.36:56081/udp
2020-05-04 11:19:53.572 INFO: [117] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] ConnectivityCheckClient.processSuccessResponse#636: Pair validated: 213.156.2.216:10000/udp/srflx -> 89.205.129.36:56081/udp/prflx (stream-d02203e7.RTP).
2020-05-04 11:19:53.572 INFO: [117] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] DefaultNominator.strategyNominateFirstValid#142: Nominate (first valid): 213.156.2.216:10000/udp/srflx -> 89.205.129.36:56081/udp/prflx (stream-d02203e7.RTP).
2020-05-04 11:19:53.572 INFO: [117] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] Agent.nominate#1846: verify if nominated pair answer again
2020-05-04 11:19:53.573 SEVERE: [117] org.ice4j.stack.NetAccessManager.handleFatalError: Unexpected Error!
java.lang.NullPointerException
	at org.ice4j.socket.MergingDatagramSocket.initializeActive(MergingDatagramSocket.java:577)
	at org.ice4j.ice.ComponentSocket.propertyChange(ComponentSocket.java:174)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.nominate(CandidatePair.java:629)
	at org.ice4j.ice.Agent.nominate(Agent.java:1847)
	at org.ice4j.ice.DefaultNominator.strategyNominateFirstValid(DefaultNominator.java:144)
	at org.ice4j.ice.DefaultNominator.propertyChange(DefaultNominator.java:120)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.validate(CandidatePair.java:667)
	at org.ice4j.ice.IceMediaStream.addToValidList(IceMediaStream.java:668)
	at org.ice4j.ice.Agent.validatePair(Agent.java:1811)
	at org.ice4j.ice.ConnectivityCheckClient.processSuccessResponse(ConnectivityCheckClient.java:638)
	at org.ice4j.ice.ConnectivityCheckClient.processResponse(ConnectivityCheckClient.java:405)
	at org.ice4j.stack.StunClientTransaction.handleResponse(StunClientTransaction.java:314)
	at org.ice4j.stack.StunStack.handleMessageEvent(StunStack.java:1040)
	at org.ice4j.stack.MessageProcessingTask.run(MessageProcessingTask.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-04 11:19:53.585 INFO: [147] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] ConnectivityCheckClient$PaceMaker.run#919: Pair failed: 10.32.0.3:10000/udp/host -> 192.168.8.100:55505/udp/host (stream-d02203e7.RTP)
2020-05-04 11:19:53.606 INFO: [68] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] ConnectivityCheckClient$PaceMaker.run#919: Pair failed: 10.32.0.2:10000/udp/host -> 192.168.8.100:55505/udp/host (stream-d02203e7.RTP)
2020-05-04 11:19:53.627 INFO: [147] [confId=cd69d8a54b43d12a gid=ff7a5f stats_id=Reyna-XiE conf_name=standup ufrag=ct91h1e7ffo1f8 epId=d02203e7 local_ufrag=ct91h1e7ffo1f8] ConnectivityCheckClient$PaceMaker.run#919: Pair failed: 10.32.0.1:10000/udp/host -> 192.168.8.100:55505/udp/host (stream-d02203e7.RTP)
```

## Expected Behavior
Stable meeting join procedure

## Steps to reproduce
Join group meeting (>2 participants) multiple times and check if connection is working / check jvb.log for errors.

## Environment details
Debian stretch
8 GB RAM
10-20% CPU usage at the time when error occurs

Jitsi Meet latest version in combination with jitsi-meet-tokens authentication via the latest (12.x) version of Prosody

**Comment by debfx** [comment]
Since this is very likely a bug in the ice4j component I've opened an issue there: jitsi/ice4j#205

**Comment by debfx** [comment]
This bug has been fixed in ice4j so the ice4j dependency in this repo needs to be bumped to >= v3.0-17-ged63ae8
