### ISSUE TITLE
Unexpected Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mback2k** [jitsi/jitsi-videobridge#1289]
## Description
Unexpected Error: java.lang.NullPointerException

## Current behavior
```
Jun 02, 2020 1:48:49 PM org.ice4j.stack.NetAccessManager handleFatalError
SEVERE: Unexpected Error!
java.lang.NullPointerException
	at org.ice4j.socket.MergingDatagramSocket.initializeActive(MergingDatagramSocket.java:577)
	at org.ice4j.ice.ComponentSocket.propertyChange(ComponentSocket.java:174)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.nominate(CandidatePair.java:629)
	at org.ice4j.ice.Agent.nominate(Agent.java:1847)
	at org.ice4j.ice.DefaultNominator.strategyNominateFirstValid(DefaultNominator.java:144)
	at org.ice4j.ice.DefaultNominator.propertyChange(DefaultNominator.java:120)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.validate(CandidatePair.java:667)
	at org.ice4j.ice.IceMediaStream.addToValidList(IceMediaStream.java:668)
	at org.ice4j.ice.Agent.validatePair(Agent.java:1811)
	at org.ice4j.ice.ConnectivityCheckClient.processSuccessResponse(ConnectivityCheckClient.java:638)
	at org.ice4j.ice.ConnectivityCheckClient.processResponse(ConnectivityCheckClient.java:405)
	at org.ice4j.stack.StunClientTransaction.handleResponse(StunClientTransaction.java:314)
	at org.ice4j.stack.StunStack.handleMessageEvent(StunStack.java:1040)
	at org.ice4j.stack.MessageProcessingTask.run(MessageProcessingTask.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior
At least provide a better error message than the NullPointerException.

## Possible Solution
Unknown.

## Steps to reproduce
Unknown.

# Environment details
- JVB behind firewall and docker NAT with TCP harvester and public IP set in configuration
- STUN and TURN is also configured for P2P connections

**Comment by mback2k** [comment]
Here is the same stack trace in the most recently released JVB:
```
Jun 02, 2020 1:56:17 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: verify if nominated pair answer again
Jun 02, 2020 1:56:17 PM org.ice4j.stack.NetAccessManager handleFatalError
SEVERE: Unexpected Error!
java.lang.NullPointerException
	at org.ice4j.socket.MergingDatagramSocket.initializeActive(MergingDatagramSocket.java:577)
	at org.ice4j.ice.ComponentSocket.propertyChange(ComponentSocket.java:174)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.nominate(CandidatePair.java:629)
	at org.ice4j.ice.Agent.nominate(Agent.java:1847)
	at org.ice4j.ice.DefaultNominator.strategyNominateFirstValid(DefaultNominator.java:144)
	at org.ice4j.ice.DefaultNominator.propertyChange(DefaultNominator.java:120)
	at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:870)
	at org.ice4j.ice.CandidatePair.validate(CandidatePair.java:667)
	at org.ice4j.ice.IceMediaStream.addToValidList(IceMediaStream.java:668)
	at org.ice4j.ice.Agent.validatePair(Agent.java:1811)
	at org.ice4j.ice.ConnectivityCheckClient.processSuccessResponse(ConnectivityCheckClient.java:638)
	at org.ice4j.ice.ConnectivityCheckClient.processResponse(ConnectivityCheckClient.java:405)
	at org.ice4j.stack.StunClientTransaction.handleResponse(StunClientTransaction.java:314)
	at org.ice4j.stack.StunStack.handleMessageEvent(StunStack.java:1040)
	at org.ice4j.stack.MessageProcessingTask.run(MessageProcessingTask.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by debfx** [comment]
duplicated of #1243

**Comment by mback2k** [comment]
yep, I guess the issue can be continued here: https://github.com/jitsi/ice4j/issues/205
