### ISSUE TITLE
videobridge does not automatically restart after crash (on debian using systemd service file)

### ISSUE THREAD

**Issue by abeluck** [jitsi/jitsi-videobridge#1353]
## Description

When using the debian package and the included systemd service to manage the JVB lifecycle, if the JVB's JVM crashes due to OOM conditions, it does not automatically restart. 

---

## Current behavior

On a OOM condition like so:

```
020-07-22 23:57:50.318 SEVERE: [27] AbstractHealthCheckService.run#185: Health check failed in PT32.766281S:
java.lang.Exception: Performing a health check took too long: PT32.766281S
        at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:170)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f5244829000, 16384, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
2020-07-22 23:57:52.435 INFO: [25] VideobridgeExpireThread.expire#144: Running expire()
```

...the service stays dead.

---

## Expected Behavior

The service should be automatically restarted by systemd

---

## Possible Solution

Use the [Restart=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) directive in the service file.

In particular, I propose `Restart=on-failure` to handle failure cases.

---

## Steps to reproduce

1. Start JVB via systemd
2. Get the pid of the process
3. `kill -s SIGQUIT $pid` to simulate a crash (SIGQUIT is an "unclean" signal according to systemd)
4. Observe that JVB is dead and remains dead

---

# Environment details

* debian 10.4
* jitsi-videobridge2 2.1-273-g072dd44b-1
---

**Comment by saghul** [comment]
Sounds reasonable, any chance you can open a PR?
