### ISSUE TITLE
JVB octo stats missing following update

### ISSUE THREAD

**Issue by RobHooper** [jitsi/jitsi-videobridge#1411]
## Description
---
Since patching Jitsi this morning I've started seeing the following error in the JVB logs. I have also found that less stats are reported from colibri/stats. 
From what I can tell nothing else seems affected but I haven't thoroughly tested yet.

## Current behavior
---
```
# tail -f /var/log/jitsi/jvb.log
2020-09-07 10:33:56.654 SEVERE: [22] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.run() threw an exception.
kotlin.KotlinNullPointerException
	at org.jitsi.videobridge.octo.OctoRelayService.getStats(OctoRelayService.kt:88)
	at org.jitsi.videobridge.stats.VideobridgeStatistics.generate0(VideobridgeStatistics.java:477)
	at org.jitsi.videobridge.stats.VideobridgeStatistics.generate(VideobridgeStatistics.java:157)
	at org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.doRun(StatsManager.java:310)
	at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

# curl -sS localhost:8080/colibri/stats | json_pp | grep 'octo' | sort
   "octo_conferences" : 0,
   "octo_endpoints" : 0,
```

## Expected Behavior
---
I expect it to not print a severe error every 5 seconds...

Also, these are the stats I was getting from colibri/stats pre-update. 
```
# curl -sS localhost:8080/colibri/stats | json_pp | grep 'octo' | sort
   "octo_conferences" : 0,
   "octo_endpoints" : 0,
   "octo_receive_bitrate" : 0,
   "octo_receive_packet_rate" : 0,
   "octo_send_bitrate" : 0,
   "octo_send_packet_rate" : 0,
   "total_bytes_received_octo" : 0,
   "total_bytes_sent_octo" : 0,
   "total_packets_dropped_octo" : 0,
   "total_packets_received_octo" : 0
   "total_packets_sent_octo" : 0,

```

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
This happened following the upgrade of jitsi-videobridge2 from version 2.1-273-g072dd44b-1 to version 2.1-304-g8488f77d-1.

This server is just hosting jitsi-videobridge2, the main server it sits behind doesn't have this issue. 

More info:
```
# java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)


# cat /etc/jitsi/videobridge/config 
JVB_HOSTNAME=ex2.example.co.uk
JVB_HOST=
JVB_PORT=5347
JVB_SECRET=redacted
JVB_OPTS="--apis=rest,"
JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"


# cat /etc/jitsi/videobridge/sip-communicator.properties 
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=redacted
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=jitsi.example.co.uk
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.jitsi.example.co.uk
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=redacted
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.jitsi.example.co.uk
org.jitsi.videobridge.xmpp.user.shard.DISABLE_CERTIFICATE_VERIFICATION=true
org.jitsi.videobridge.octo.BIND_ADDRESS=10.106.0.3
org.jitsi.videobridge.octo.PUBLIC_ADDRESS=redacted
org.jitsi.videobridge.octo.BIND_PORT=4096
org.jitsi.videobridge.REGION=region1
```

**Comment by bbaldino** [comment]
Can you include the full JVB log?

**Comment by bbaldino** [comment]
Ok, @bgrozev spotted it without the log.  I've got a fix here: https://github.com/jitsi/jitsi-videobridge/pull/1419.  You should see, though, an error message at the start of your JVB log complaining about the incorrect Octo configuration/startup error.

**Comment by bgrozev** [comment]
Please re-open if it happens with master after #1419
