### ISSUE TITLE
NoClassDefFoundError JdkDeserializers since 2.1-273-g072dd44b-1

### ISSUE THREAD

**Issue by Cybso** [jitsi/jitsi-videobridge#1412]
## Description
---

Jvb floods the log file with the following messages:

```
Exception in thread "Global IO pool-3" java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.deser.std.JdkDeserializers
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1852)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:167)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:131)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4389)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4198)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3188)
	at org.jitsi.videobridge.message.BridgeChannelMessage$Companion.parse(BridgeChannelMessage.kt:373)
	at org.jitsi.videobridge.message.BridgeChannelMessage.parse(BridgeChannelMessage.kt)
	at org.jitsi.videobridge.AbstractEndpointMessageTransport.onMessage(AbstractEndpointMessageTransport.java:75)
	at org.jitsi.videobridge.EndpointMessageTransport.onDataChannelMessage(EndpointMessageTransport.java:192)
	at org.jitsi.videobridge.datachannel.DataChannel.onIncomingMsg(DataChannel.java:131)
	at org.jitsi.videobridge.datachannel.DataChannelStack.onIncomingDataChannelPacket(DataChannelStack.java:84)
	at org.jitsi.videobridge.Endpoint$DataChannelHandler.consume(Endpoint.java:1465)
	at org.jitsi.videobridge.Endpoint.lambda$null$6(Endpoint.java:888)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Since this started we've also observed problems with random black screen instead of video in some conferences.

I've traced this down to the upgrade from 2.1-202-g5f9377b9-1 to 2.1-273-g072dd44b-1, while 2.1-304-g8488f77d-1 is still affected. 

# Environment details
---

Debian 10 buster with adoptopenjdk-8-hotspot-jre-amd64 (but java-11-openjdk-amd64 doesn't work either).

**Comment by licaon-kter** [comment]
Seeing the same for HEAD (313feee88fa4e2dfd3cf0ab61a382f94ba9a7f55) for a while now: Debian Buster, arm64

**Comment by JonathanLennox** [comment]
This is apparently usually a symptom of version skew in Jackson dependency libraries.

From your description it looks like you're building from source, so can you show what `mvn dependency:tree -Dincludes='*jackson*'` outputs?

**Comment by licaon-kter** [comment]
Yes, building debs from source
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] jvb-api-parent                                                     [pom]
[INFO] jvb-api-common                                                     [jar]
[INFO] jvb-api-client                                                     [jar]
[INFO] jitsi-videobridge                                                  [jar]
[INFO] jvb-parent                                                         [pom]
[INFO]
[INFO] ----------------------< org.jitsi:jvb-api-parent >----------------------
[INFO] Building jvb-api-parent 2.1-314-g313feee8                          [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jvb-api-parent ---
[INFO]
[INFO] ----------------------< org.jitsi:jvb-api-common >----------------------
[INFO] Building jvb-api-common 2.1-314-g313feee8                          [2/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jvb-api-common ---
[INFO] org.jitsi:jvb-api-common:jar:2.1-314-g313feee8
[INFO] \- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.0:compile
[INFO]
[INFO] ----------------------< org.jitsi:jvb-api-client >----------------------
[INFO] Building jvb-api-client 2.1-314-g313feee8                          [3/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jvb-api-client ---
[INFO] org.jitsi:jvb-api-client:jar:2.1-314-g313feee8
[INFO] +- org.jitsi:jvb-api-common:jar:2.1-314-g313feee8:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.0:compile
[INFO] +- io.ktor:ktor-client-jackson:jar:1.3.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.3:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] \- com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.11.0:compile
[INFO]
[INFO] --------------------< org.jitsi:jitsi-videobridge >---------------------
[INFO] Building jitsi-videobridge 2.1-314-g313feee8                       [4/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jitsi-videobridge ---
[INFO] org.jitsi:jitsi-videobridge:jar:2.1-314-g313feee8
[INFO] +- org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.30.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.1:compile
[INFO] +- com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.11.0:compile
[INFO] \- io.sentry:sentry:jar:1.7.30:runtime
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile
[INFO]
[INFO] ------------------------< org.jitsi:jvb-parent >------------------------
[INFO] Building jvb-parent 2.1-SNAPSHOT                                   [5/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jvb-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] jvb-api-parent 2.1-314-g313feee8 ................... SUCCESS [  4.737 s]
[INFO] jvb-api-common 2.1-314-g313feee8 ................... SUCCESS [  1.377 s]
[INFO] jvb-api-client 2.1-314-g313feee8 ................... SUCCESS [  1.567 s]
[INFO] jitsi-videobridge 2.1-314-g313feee8 ................ SUCCESS [  3.139 s]
[INFO] jvb-parent 2.1-SNAPSHOT ............................ SUCCESS [  0.034 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.948 s
[INFO] Finished at: 2020-09-08T15:09:57Z
[INFO] ------------------------------------------------------------------------
```

**Comment by licaon-kter** [comment]
Thanks
