### ISSUE TITLE
Parameter specified as non-null is null: parameter statsCollector

### ISSUE THREAD

**Issue by pat-s** [jitsi/jitsi-videobridge#1503]
After updating my Jitsi instance (v2.0.5142) I see the following in `/var/log/jitsi/jvb.log`.

```
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.jitsi.videobridge.rest.binders.ServiceBinder.<init>, parameter statsCollector
        at org.jitsi.videobridge.rest.binders.ServiceBinder.<init>(ServiceBinder.kt)
        at org.jitsi.videobridge.rest.root.Application.<init>(Application.java:37)
        at org.jitsi.videobridge.MainKt.main(Main.kt:129)
```

Looks like a parameter is not set either on my side or upstream. 
Does someone have an how I can solve this to get the videobridge back up?

**Comment by bbaldino** [comment]
Can you post the full jvb log?

**Comment by pat-s** [comment]
<details>
<summary>Details</summary>

```
OpenJDK 64-Bit Server VM warning: Ignoring option UseConcMarkSweepGC; support was removed in 14.0
2020-10-22 13:52:10.456 INFO: [1] JitsiConfig.<clinit>#46: Initialized newConfig: merge of system properties,/etc/jitsi/videobridge/jvb.conf: 1,system properties,reference.conf @ jar:file:/usr/share/jitsi-videobridge/jitsi-videobridge.jar!/reference.conf: 1,reference.conf @ jar:file:/usr/share/jitsi-videobridge/lib/jitsi-media-transform-1.0-198-g1babb83.jar!/reference.conf: 1,reference.conf @ jar:file:/usr/share/jitsi-videobridge/lib/ice4j-3.0-22-g67ffceb.jar!/reference.conf: 1
2020-10-22 13:52:10.491 INFO: [1] ReadOnlyConfigurationService.reloadConfiguration#51: loading config file at path /etc/jitsi/videobridge/sip-communicator.properties
2020-10-22 13:52:10.493 INFO: [1] JitsiConfig.<clinit>#67: Initialized legacyConfig: sip communicator props (no description provided)
2020-10-22 13:52:10.496 INFO: [1] JitsiConfig$Companion.reloadNewConfig#83: Reloading the Typesafe config source (previously reloaded 0 times).
2020-10-22 13:52:11.604 INFO: [14] org.ice4j.ice.harvest.StunMappingCandidateHarvester.discover: Discovered public address 159.100.244.208:54600/udp from STUN server 193.123.38.23:443/udp using local address 159.100.244.208:0/udp
2020-10-22 13:52:11.790 INFO: [1] LastNReducer.<init>#60: LastNReducer with reductionScale: 0.75 recoverScale: 1.25 impactTime: PT1M minLastN: 0 maxEnforcedLastN: 40
2020-10-22 13:52:11.801 INFO: [1] TaskPools.<clinit>#81: TaskPools detected 2 processors, creating the CPU pool with that many threads
2020-10-22 13:52:11.901 WARNING: [20] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#673: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:668)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-22 13:52:11.929 INFO: [1] UlimitCheck.printUlimits#115: Running with open files limit 65000 (hard 65000), thread limit 65000 (hard 65000).
2020-10-22 13:52:11.930 INFO: [1] VideobridgeExpireThread.start#88: Starting with 60 second interval.
2020-10-22 13:52:11.933 INFO: [1] HealthChecker.start#118: Started with interval=10000, timeout=PT30S, maxDuration=PT3S, stickyFailures=false.
2020-10-22 13:52:12.007 INFO: [1] MainKt.main#101: Not starting CallstatsService, disabled in configuration.
2020-10-22 13:52:12.019 INFO: [1] MainKt.main#110: Starting public http server
2020-10-22 13:52:12.124 INFO: [1] ColibriWebSocketService.<init>#40: Base URL: wss://zhrusergroup.cynkra.dev:443/colibri-ws/default-id
2020-10-22 13:52:12.163 INFO: [1] org.eclipse.jetty.util.log.Log.initialized: Logging initialized @2601ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-10-22 13:52:12.235 INFO: [1] ColibriWebSocketService.registerServlet#65: Registering servlet at /colibri-ws/*, baseUrl = wss://zhrusergroup.cynkra.dev:443/colibri-ws/default-id
2020-10-22 13:52:12.255 INFO: [1] org.eclipse.jetty.server.Server.doStart: jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 14.0.1+7-Ubuntu-1ubuntu1
2020-10-22 13:52:12.371 INFO: [1] org.eclipse.jetty.server.handler.ContextHandler.doStart: Started o.e.j.s.ServletContextHandler@346939bf{/,null,AVAILABLE}
2020-10-22 13:52:12.409 INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@132ddbab{HTTP/1.1,[http/1.1]}{0.0.0.0:9090}
2020-10-22 13:52:12.409 INFO: [1] org.eclipse.jetty.server.Server.doStart: Started @2847ms
2020-10-22 13:52:12.410 INFO: [1] MainKt.main#128: Starting private http server
2020-10-22 13:52:12.536 INFO: [1] org.eclipse.jetty.server.Server.doStart: jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 14.0.1+7-Ubuntu-1ubuntu1
2020-10-22 13:52:13.611 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Health registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Health will be ignored. 
2020-10-22 13:52:13.613 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Version registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Version will be ignored. 
2020-10-22 13:52:14.081 INFO: [1] org.eclipse.jetty.server.handler.ContextHandler.doStart: Started o.e.j.s.ServletContextHandler@10641c09{/,null,AVAILABLE}
2020-10-22 13:52:14.084 INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@34f392be{HTTP/1.1,[http/1.1]}{127.0.0.1:8080}
2020-10-22 13:52:14.084 INFO: [1] org.eclipse.jetty.server.Server.doStart: Started @4522ms
2020-10-22 13:52:16.903 WARNING: [20] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#673: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:668)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-22 13:52:17.859 INFO: [12] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Using org.ice4j.ice.harvest.StunMappingCandidateHarvester, face=/159.100.244.208, mask=/159.100.244.208
2020-10-22 13:52:17.860 INFO: [12] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Initialized mapping harvesters (delay=7311ms).  stunDiscoveryFailed=false
2020-10-22 13:52:21.858 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.003841S. Sticky failure: false
2020-10-22 13:52:21.936 WARNING: [20] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#673: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve auth.zhrusergroup.cynkra.dev</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1059)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-22 13:52:21.946 WARNING: [47] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve auth.zhrusergroup.cynkra.dev</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-22 13:52:21.948 WARNING: [47] [hostname=localhost id=shard] MucClient$1.connectionClosedOnError#317: Closed on error:
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve auth.zhrusergroup.cynkra.dev</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-22 13:52:27.604 INFO: [20] [hostname=localhost id=shard] MucClient$1.connected#271: Connected.
2020-10-22 13:52:27.610 INFO: [20] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#680: Logging in.
2020-10-22 13:52:27.806 INFO: [20] [hostname=localhost id=shard] MucClient$MucWrapper.join#788: Joined MUC: jvbbrewery@internal.auth.zhrusergroup.cynkra.dev
2020-10-22 13:52:31.853 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.000034S. Sticky failure: false
2020-10-22 13:52:41.853 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.000021S. Sticky failure: false
2020-10-22 13:52:51.854 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.000077S. Sticky failure: false
2020-10-22 13:53:01.854 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.000069S. Sticky failure: false
2020-10-22 13:53:11.854 INFO: [27] HealthChecker.run#170: Performed a successful health check in PT0.000025S. Sticky failure: false
2020-10-22 13:53:11.932 INFO: [26] VideobridgeExpireThread.expire#140: Running expire()
OpenJDK 64-Bit Server VM warning: Ignoring option UseConcMarkSweepGC; support was removed in 14.0
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.jitsi.videobridge.rest.binders.ServiceBinder.<init>, parameter statsCollector
	at org.jitsi.videobridge.rest.binders.ServiceBinder.<init>(ServiceBinder.kt)
	at org.jitsi.videobridge.rest.root.Application.<init>(Application.java:37)
	at org.jitsi.videobridge.MainKt.main(Main.kt:129)
OpenJDK 64-Bit Server VM warning: Ignoring option UseConcMarkSweepGC; support was removed in 14.0
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.jitsi.videobridge.rest.binders.ServiceBinder.<init>, parameter statsCollector
	at org.jitsi.videobridge.rest.binders.ServiceBinder.<init>(ServiceBinder.kt)
	at org.jitsi.videobridge.rest.root.Application.<init>(Application.java:37)
	at org.jitsi.videobridge.MainKt.main(Main.kt:129)
```

</details>

There is also a [similar post](https://community.jitsi.org/t/error-when-starting-jvb-using-jvb-sh-parameter-specified-as-non-null-is-null-method-org-jitsi-videobridge-rest-binders-servicebinder-init-parameter-statscollector/81582) on the forum.

**Comment by bbaldino** [comment]
Thanks, I've made a PR with a fix

**Comment by pat-s** [comment]
That was quick, thanks!
