### ISSUE TITLE
Unable to run the application from source

### ISSUE THREAD

**Issue by jpsingarayar** [jitsi/jitsi-videobridge#1592]
When trying to run the application from the source, Im getting the following error

```
git clone https://github.com/jitsi/jitsi-videobridge.git
cd jitsi-videobridge
cd jvb
mvn compile exec:exec -Dexec.executable=java -Dexec.args="-cp %classpath org.jitsi.videobridge.MainKt -Djava.library.path=/Users/myuser/OSProjects/jitsi-videobridge/jvb/lib/native/linux-64 -Djava.util.logging.config.file=/Users/myuser/OSProjects/jitsi-videobridge/jvb/lib/logging.properties -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=.jitsi-videobridge "


Feb 28, 2021 11:55:54 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Initialized newConfig: merge of application.conf @ file:/Users/myuser/OSProjects/jitsi-videobridge/jvb/target/classes/application.conf: 1,system properties,reference.conf @ file:/Users/myuser/OSProjects/jitsi-videobridge/jvb/target/classes/reference.conf: 1,reference.conf @ jar:file:/Users/myuser/.m2/repository/org/jitsi/jitsi-media-transform/1.0-220-gaa6c4db/jitsi-media-transform-1.0-220-gaa6c4db.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/myuser/.m2/repository/org/jitsi/ice4j/3.0-22-g67ffceb/ice4j-3.0-22-g67ffceb.jar!/reference.conf: 1
Feb 28, 2021 11:55:54 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: net.java.sip.communicator.SC_HOME_DIR_LOCATION not set
Feb 28, 2021 11:55:54 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Initialized legacyConfig: sip communicator props (no description provided)
Exception in thread "main" java.lang.IllegalStateException: cmdLine.getOptionValue("--apis") must not be null
	at org.jitsi.videobridge.MainKt.main(Main.kt:72)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)


```

Not sure what to pass on for `--apis` through command line.

**Comment by bgrozev** [comment]
You should be able to just pass `--apis=`. It's something we need to clean up.

**Comment by AmityTek** [comment]
Even if I pass `--apis=` I've got the same issue

**Comment by bgrozev** [comment]
I don't understand why this would occur if you pass `--apis=`. Regardless, it's not intended to be required anymore. Can you test if #1625 fixes the issue for you?
