### ISSUE TITLE
Sctp send error: : Transport endpoint is not connected

### ISSUE THREAD

**Issue by lyubomir** [jitsi/jitsi-videobridge#16]
org.jitsi.videobridge.Endpoint.error() SCTP error, endpoint: aa53d346
java.io.IOException: Failed to open new chanel on sid: 0
at org.jitsi.videobridge.SctpConnection.openChannel(SctpConnection.java:917)
at org.jitsi.videobridge.SctpConnection.getDefaultDataStream(SctpConnection.java:366)
at org.jitsi.videobridge.Endpoint.sendMessageOnDataChannel(Endpoint.java:283)
at org.jitsi.videobridge.Conference.sctpConnectionReady(Conference.java:1072)
at org.jitsi.videobridge.Conference.access$000(Conference.java:33)
at org.jitsi.videobridge.Conference$1.onSctpConnectionReady(Conference.java:152)
at org.jitsi.videobridge.SctpConnection.notifySctpConnectionReadyInEventDispatcher(SctpConnection.java:551)
at org.jitsi.videobridge.SctpConnection.access$300(SctpConnection.java:43)
at org.jitsi.videobridge.SctpConnection$3.run(SctpConnection.java:531)
at net.java.sip.communicator.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:110)
at net.java.sip.communicator.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:16)
at net.java.sip.communicator.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:219)

A known workaround is to wait long enough between Conference.sctpConnectionReady and SctpConnection.openChannel.

**Comment by yanas** [comment]
@lyubomir @paweldomas this is now a year old issue. Could you please confirm that it is still a valid problem and isn't fixed?

**Comment by paweldomas** [comment]
It has been fixed some time ago.
