### ISSUE TITLE
latest Commits (Compile failed)

### ISSUE THREAD

**Issue by DoM1niC** [jitsi/jitsi-videobridge#1688]
latest 2 Commits compiling fail... :(

**Building commands**
```
cd jitsi-videobridge
git reset --hard
git pull origin master
mvn clean
mvn install
```
**Log**
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 s - in org.jitsi.videobridge.xmpp.config.XmppClientConnectionConfigTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[ERROR]   MediaSourceFactoryTest.createMediaSource:75 »  java.lang.reflect.InaccessibleO...
[INFO]
[ERROR] Tests run: 360, Failures: 0, Errors: 6, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jvb-parent 2.1-SNAPSHOT:
[INFO]
[INFO] jvb-parent ......................................... SUCCESS [  0.655 s]
[INFO] jvb-api-parent ..................................... SUCCESS [  0.053 s]
[INFO] jvb-api-common ..................................... SUCCESS [ 11.619 s]
[INFO] jvb-api-client ..................................... SUCCESS [ 18.581 s]
[INFO] jitsi-videobridge .................................. FAILURE [01:19 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2021-07-17T16:52:07+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jitsi-videobridge: There are test failures.
[ERROR]
[ERROR] Please refer to /mnt/e/Git/jitsi/jitsi-videobridge/jvb/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jitsi-videobridge
```

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Which java version do you use?

**Comment by DoM1niC** [comment]
**Java**
```
openjdk version "11.0.12-ea" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12-ea+6-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.12-ea+6-post-Debian-1, mixed mode, sharing)
```
**More Log**
```
[INFO] Running org.jitsi.videobridge.xmpp.MediaSourceFactoryTest
Jul 17, 2021 5:22:44 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Initialized newConfig: merge of application.conf @ file:/mnt/e/Git/jitsi/jitsi-videobridge/jvb/target/classes/application.conf: 1,system properties,reference.conf @ file:/mnt/e/Git/jitsi/jitsi-videobridge/jvb/target/classes/reference.conf: 1,reference.conf @ jar:file:/home/dom1nic/.m2/repository/org/jitsi/jitsi-media-transform/1.0-245-g21a5fe3/jitsi-media-transform-1.0-245-g21a5fe3.jar!/reference.conf: 1,reference.conf @ jar:file:/home/dom1nic/.m2/repository/org/jitsi/ice4j/3.0-33-g311a495/ice4j-3.0-33-g311a495.jar!/reference.conf: 1
Jul 17, 2021 5:22:44 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: net.java.sip.communicator.SC_HOME_DIR_LOCATION not set
Jul 17, 2021 5:22:44 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Initialized legacyConfig: sip communicator props (no description provided)
Jul 17, 2021 5:22:44 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Unprocessed source groups: Optional[<ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>]
[ERROR] Tests run: 7, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 1.112 s <<< FAILURE! - in org.jitsi.videobridge.xmpp.MediaSourceFactoryTest
[ERROR] createMediaSource  Time elapsed: 1.051 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

[ERROR] createMediaSources1  Time elapsed: 0.011 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

[ERROR] createMediaSources2  Time elapsed: 0.004 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

[ERROR] createMediaSources3  Time elapsed: 0.002 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

[ERROR] createMediaSources4  Time elapsed: 0.002 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

[ERROR] testEmptySimGroup  Time elapsed: 0.026 s  <<< ERROR!
org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @7f7b6639
        at org.jitsi.videobridge.xmpp.MediaSourceFactoryTest.createMediaSource(MediaSourceFactoryTest.java:75)

~~~ Kotest Configuration ~~~
-> Parallelization factor: 1
-> Concurrent specs: null
-> Global concurrent tests: 1
-> Dispatcher affinity: true
-> Default test timeout: 600000ms
-> Default test order: Sequential
-> Default isolation mode: SingleInstance
-> Global soft assertions: false
-> Write spec failure file: false
-> Fail on ignored tests: false
-> Spec execution order: SpecExecutionOrder
-> Remove test name whitespace: false
-> Append tags to test names: false
-> Extensions
  - io.kotest.engine.extensions.SystemPropertyTagExtension
  - io.kotest.core.extensions.RuntimeTagExtension
  - io.kotest.engine.extensions.RuntimeTagExpressionExtension

```

### Jicofo and Jigasi all is fine

**Comment by DoM1niC** [comment]
Ok Java 8 JDK fixed my Problem but THX anyway !!!

**Comment by JonathanLennox** [comment]
https://github.com/jitsi/jitsi-videobridge/pull/1686 should fix this, once it's landed.
