### ISSUE TITLE
Changing UDP port causes some problems

### ISSUE THREAD

**Issue by bdewoop** [jitsi/jitsi-videobridge#1913]
### Description:

As i follow some instructions to change the jvb-udp-port from 10000 to something else the port is changed but the videobridge causes some problems.

Here is a logentry after the switch from udp-10000 to udp-3479. Suddenly the videobridge is using only private-IPs. This entry appears for every client every 10 seconds. 

`JVB 2022-06-13 16:46:01.855 INFO: [61] [xx] ConnectivityCheckClient$PaceMaker.run#943: Pair failed: 172.27.xx.xx:3479/udp/host -> 192.0.0.xx:52856/udp/host (stream-aa7c8d43.RTP)
JVB 2022-06-13 16:46:01.876 WARNING: [61] [xx ] ConnectivityCheckClient.startCheckForPair#375: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0x945F875D8101F39CFA4EF7E4]
java.lang.IllegalArgumentException: No socket found for 172.27.xx.xx:3479/udp->192.0.0.xx:55391/udp
        at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:631)
        at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:581)
        at org.ice4j.stack.StunClientTransaction.sendRequest0(StunClientTransaction.java:267)
        at org.ice4j.stack.StunClientTransaction.sendRequest(StunClientTransaction.java:245)
        at org.ice4j.stack.StunStack.sendRequest(StunStack.java:680)
        at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:333)
        at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:229)
        at org.ice4j.ice.ConnectivityCheckClient$PaceMaker.run(ConnectivityCheckClient.java:939)
        at org.ice4j.util.PeriodicRunnable.executeRun(PeriodicRunnable.java:206)
        at org.ice4j.util.PeriodicRunnable$$Lambda$442/0x0000000000000000.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:836)`

I thought i can prevent using the private IPs but activating "advertise-private-candidates = false" cannot fix this because it gets never queried.

I hope you can help to fix this issue.

### Steps to reproduce:

1. open `/etc/jitsi/videobridge/sip-communicator.properties`
2. add `org.jitsi.videobridge.SINGLE_PORT_HARVESTER_PORT=3479`
3. restart the videobridge
4. connect with 2 or more clients and look at the log

Step 1 is also possible with the new arguments for the jvb.conf so instead of using step 1 and 2 you can also use 
5. open `/etc/jitsi/videobridge/jvb.conf`
6. add `    ice {
        udp {
            port = 3479
        }}`.

### Expected behavior:

Changing the UDP port is working and the videobridge is usable.

### Actual behavior:

Activating the options for changing the port will make the systems unusable.

### Server information:

- Jitsi Meet version: 2.0.7287 (2022-05-09)
- Operating System: Debian 11

### Client information:

- Browser / app version: Safari, Vivaldi, Chrome, Brave, Firefox + iOS and Android Browsers (especially Safari was the most painfull experience with this)
- Operating System: Windows, Linux, iOS, Android and MacOS

### Additional information:

We are using a scalable setup so we have a server with jitsi meet full install and two seperate videobridges. Additionally we are using the [TURN setup](https://jitsi.github.io/handbook/docs/devops-guide/turn) on port 443 and wanted to change the ports with [This](https://community.jitsi.org/t/changing-default-udp-port-10000-to-something-else/31205) and [This](https://github.com/jitsi/jitsi-videobridge/blob/stable/jitsi-meet_7287/CONFIG.md). I dont know if that helps but i thought the information is helpfull if someone of you wants to reproduce the problem.

**Comment by bgrozev** [comment]
What jvb version? This exception is harmless and suppressed recently. If it only happens with the new port you probably need to adjust firewall settings.

**Comment by bdewoop** [comment]
Sorry, i thought the version is for the whole release of jitsi, jicofo, jvb etc. 
JVB version is 2.1-681-g3544ed05-1
The Firewall is completely open for this server so it cant come from the firewallside :/

**Comment by damencho** [comment]
What about port forwarding? Is that correct and working?

**Comment by DeamonMV** [comment]
I have the same situation https://github.com/jitsi-contrib/jitsi-helm/issues/58
Version of jvb is `image: jitsi/jvb:stable-6865`

**Comment by bgrozev** [comment]
Please re-open if this still happens
