### ISSUE TITLE
Deploying multiple video bridges does not work properly

### ISSUE THREAD

**Issue by IOXusu** [jitsi/jitsi-videobridge#2045]
Deploying multiple video bridges does not work properly

## Description
After deploying according to the document, I am unable to have normal audio and video meetings
My Steps: https://gist.github.com/danmaby/0eb5d8f7d459dfd0cba1533332ee9268

## Current behavior
This is my second video bridge log, "/var/log/jitsi/jvb.log" 

`JVB 2023-08-29 03:42:14.687 WARNING: [28] [hostname=localhost id=shard] MucClient.setPresenceExtensions#467: Cannot set presence extension: not connected.
JVB 2023-08-29 03:42:15.423 WARNING: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$9#640: Error connecting:
org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [localhost:5222] (localhost/127.0.0.1:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused)
	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:664)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:849)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$9(MucClient.java:635)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

## Expected Behavior
According to the reference steps, the meet server should receive the following content
grep 'Added new videobridge' /var/log/jitsi/jicofo.log
Bug but I did not see it

![WX20230829-114934@2x](https://github.com/jitsi/jitsi-videobridge/assets/9004918/2f2ee56a-9ea6-49a3-98ee-e3635fb6e08a)

![WX20230829-115148@2x](https://github.com/jitsi/jitsi-videobridge/assets/9004918/9f0cfda8-5276-4917-beaf-2369639b2666)

**Comment by damencho** [comment]
> After deploying according to the document,

What is that document? 

You need to set the server address to connect to prosody as it seems you are installing on new machine where proaody is not on localhost.

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by IOXusu** [comment]
Thanks,I will try it. This document ,  https://gist.github.com/danmaby/0eb5d8f7d459dfd0cba1533332ee9268 ,

**Comment by damencho** [comment]
That document is not anything official and is outdated. For example it is for the old component code for jicofo which doesn't exist for several years now.
