### ISSUE TITLE
No fingerprint declared over the signaling path with hash function: sha-256!

### ISSUE THREAD

**Issue by nsnake** [jitsi/jitsi-videobridge#268]
I used chrome connect well， but when i  use MeetRTC_iOS repo to connect to jvb it report below messages. How could fix it ? thanks.
```
JVB 2016-07-13 15:55:54.441 信息: [2224] org.jitsi.impl.neomedia.rtcp.termination.strategies.BasicRTCPTerminationStrategy.info() There are no receive streams to build report blocks for.
JVB 2016-07-13 15:55:54.462 严重: [2220] org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.error() Failed to verify and/or validate a certificate offered over the media path against fingerprints declared over the signaling path! No fingerprint declared over the signaling path with hash function: sha-256!
JVB 2016-07-13 15:55:54.462 严重: [2220] org.jitsi.impl.neomedia.transform.dtls.TlsServerImpl.error() Failed to verify and/or validate client certificate!
java.io.IOException: No fingerprint declared over the signaling path with hash function: sha-256!
	at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.verifyAndValidateCertificate(DtlsControlImpl.java:888)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.verifyAndValidateCertificate(DtlsControlImpl.java:947)
	at org.jitsi.impl.neomedia.transform.dtls.TlsServerImpl.notifyClientCertificate(TlsServerImpl.java:417)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.notifyClientCertificate(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.processClientCertificate(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1027)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$100(DtlsPacketTransformer.java:40)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$2.run(DtlsPacketTransformer.java:1256)
JVB 2016-07-13 15:55:54.464 严重: [2220] org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.error() Failed to accept a connection from a DTLS client!
java.io.IOException: No fingerprint declared over the signaling path with hash function: sha-256!
	at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.verifyAndValidateCertificate(DtlsControlImpl.java:888)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.verifyAndValidateCertificate(DtlsControlImpl.java:947)
	at org.jitsi.impl.neomedia.transform.dtls.TlsServerImpl.notifyClientCertificate(TlsServerImpl.java:417)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.notifyClientCertificate(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.processClientCertificate(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1027)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$100(DtlsPacketTransformer.java:40)
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$2.run(DtlsPacketTransformer.java:1256)
```

**Comment by nsnake** [comment]
set:
org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.verifyAndValidateCertificate=false
Works !!!!

**Comment by ibauersachs** [comment]
You do realize that this effectively turns off any certificate validation and makes the system vulnerable to effertless MitM attacks?

**Comment by lhammond** [comment]
could somebody please point me to documentation showing how to configure DTLS certs?
