### ISSUE TITLE
java.lang.NullPointerException at org.jitsi.videobridge.RtpChannel.closeStream(RtpChannel.java:663)

### ISSUE THREAD

**Issue by kgdev** [jitsi/jitsi-videobridge#385]
java.lang.NullPointerException
	at org.jitsi.videobridge.RtpChannel.closeStream(RtpChannel.java:663)
	at org.jitsi.videobridge.Channel.expire(Channel.java:383)
	at org.jitsi.videobridge.RtpChannel.expire(RtpChannel.java:1836)
	at org.jitsi.videobridge.VideobridgeExpireThread.expire(VideobridgeExpireThread.java:141)
	at org.jitsi.videobridge.VideobridgeExpireThread.run(VideobridgeExpireThread.java:216)

**Comment by bgrozev** [comment]
Please include the bridge version, so we can match the lines correctly. Any more context you might have would also help.
