### ISSUE TITLE
ComponentException : Not authorized

### ISSUE THREAD

**Issue by LuisTJap** [jitsi/jitsi-videobridge#41]
I'm trying to run jitsi videobridge 361 in Ubuntu 12.04, configured ejabberd 14.07 in port 5275, the next error is shown : 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
09:45:28.646 GRAVE: [1] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[main,5,main] and message was: not-authorized
org.xmpp.component.ComponentException: not-authorized
    at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
    at org.jitsi.videobridge.Main.main(Main.java:273)
```

Thank you in advance and good work

**Comment by bayugmail** [comment]
I used the same configuration still getting error.. hmm:

**Comment by bayugmail** [comment]
please help me:
:11:30.350 SEVERE: [1] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[main,5,main] and message was: not-authorized
org.xmpp.component.ComponentException: not-authorized
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.videobridge.Main.main(Main.java:273)
