### ISSUE TITLE
Error  SEVERE: [30] and SEVERE: [31]

### ISSUE THREAD

**Issue by webstations** [jitsi/jitsi-videobridge#531]
I installed jitsi and followed the instructions on the following page:

I have come to pata process "Run jicofo:"

but when I type the command
./jicofo.sh --host = localhost --domain = meeting.mydomain.com --secret = MYSECRET2 --user_domain = auth.meeting.mydomain.com --user_name = focus --user_password = MYSECRET3

I get the following error:

Jicofo 2017-09-07 13:52:16.392 SEVERE: [30] org.jitsi.xmpp.component.ComponentBase.run().586 Failed to send ping
java.lang.NullPointerException
        at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
        at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:34)
        at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:574)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Jicofo 2017-09-07 13:52:17.647 SEVERE: [31] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

PS: i'm using Debian 9

**Comment by mckaygerhard** [comment]
same error for me at #733

**Comment by Mebus** [comment]
Hallo,

I am seeing a similar issue and don't know how to resolve it:

```
2020-03-31 18:16:27.184 INFORMATION: [17] VideobridgeExpireThread.expire#144: Running expire()
2020-03-31 18:16:28.017 SCHWERWIEGEND: [28] ComponentMain.lambda$getConnectCallable$0#293: host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-31 18:16:29.863 INFORMATION: [18] Videobridge.createConference#326: create_conf, id=910a44e69fb74a73 gid=null logging=false
2020-03-31 18:16:29.886 INFORMATION: [18] Health.doRun#294: Performed a successful health check in 24ms. Sticky failure: false
2020-03-31 18:16:33.020 SCHWERWIEGEND: [28] ComponentMain.lambda$getConnectCallable$0#293: host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
```

Currently installed packages:

```
➜  ~ dpkg -l | grep jitsi
ii  jitsi-meet                      1.0.4335-1                  all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.3928-1                  all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.3928-1                  all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.3928-1                  all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.3928-1                  all          Configuration for web serving of Jitsi Meet
rc  jitsi-videobridge               1126-1                      amd64        WebRTC compatible Selective Forwarding Unit (SFU)
ii  jitsi-videobridge2              2.1-157-g389b69ff-1         all          WebRTC compatible Selective Forwarding Unit (SFU)
➜  ~ 
```

Mebus

**Comment by damencho** [comment]
What is your /etc/jitsi/videobridge/config?

**Comment by eri451** [comment]
@damencho  "localhost" is configured in  /etc/jitsi/videobridge/config. Should that be the jitsi domain?

**Comment by WarpMee** [comment]
crickets. what was the solution?
