### ISSUE TITLE
Busy looping in org.jitsi.impl.neomedia.MediaStreamStatsImpl.tccPacketReceived

### ISSUE THREAD

**Issue by vi** [jitsi/jitsi-videobridge#562]
Sometimes Videobridge version 995-1 starts consuming 100% of a CPU core when the load does not justify it (just two peers, for example).

`jstack` shows `tccPacketReceived` as the function that is always runnable.

```
   java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:559)
        at org.jitsi.impl.neomedia.rtcp.RTCPTCCPacket.parseFci(RTCPTCCPacket.java:198)
        at org.jitsi.impl.neomedia.rtcp.RTCPTCCPacket.getPackets(RTCPTCCPacket.java:622)
        - locked <0x0000000788001480> (a org.jitsi.impl.neomedia.rtcp.RTCPTCCPacket)
        at org.jitsi.impl.neomedia.rtp.TransportCCEngine.tccReceived(TransportCCEngine.java:358)
        at org.jitsi.impl.neomedia.MediaStreamStatsImpl.tccPacketReceived(MediaStreamStatsImpl.java:1655)
        - locked <0x00000007006e5e30> (a java.util.Collections$SynchronizedList)
        at org.jitsi.impl.neomedia.transform.rtcp.StatisticsEngine.updateReceivedMediaStreamStats(StatisticsEngine.java:1026)
        at org.jitsi.impl.neomedia.transform.rtcp.StatisticsEngine.reverseTransform(StatisticsEngine.java:923)
        at org.jitsi.impl.neomedia.transform.SinglePacketTransformer.reverseTransform(SinglePacketTransformer.java:136)
        at org.jitsi.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.reverseTransform(TransformEngineChain.java:381)
        at org.jitsi.impl.neomedia.transform.TransformInputStream.createRawPacket(TransformInputStream.java:85)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.runInReceiveThread(RTPConnectorInputStream.java:768)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.access$000(RTPConnectorInputStream.java:42)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream$3.run(RTPConnectorInputStream.java:565)
```

**Comment by bgrozev** [comment]
I looked through the code quickly and couldn't find an explanation. Can you make a heap dump the next time this happens? If it is a single RTCP packet which causes the problem we'd be able to extract it and reproduce the problem.

**Comment by vi** [comment]
Maybe something like this RTPC packet?:

```
28b0a2d3b01cf1acdd969d069cc702009cd71167cc4137e49a17d1295d89
5ef824835abfee37a68140600b9509fe305fe9ebcb48158182918e9d09a5
701efced57f447a416f7ec8db46ace96647763ca9c1bf5cf8249faacbeba
3c5d1eeba5e8a4b498aecfd17cf5f361a9db73690f334d31a89e3639b600
e9fdd90720d811dfb03565085a89d251618c8d6f9647c4d5d33a1654dc23
61c76d04e4a57c211dffb3629375d130c606b6b39dc9b9dadb474cdc46c0
2c7324eb7f31a2719a9e8d9889c2e34a990c822215a016391ebc08e95243
0ebaf8007e47d8a5f946cbd278a16f57a6c8312cc2f7613998463fe49e51
2d7c3821ed706b7d8644f7e8ce156c156c7d64296456b1e1c983d4ab1a36
0820da16cd6968d4dc748a33fd5232227d2ab1aa7d4bbcf44c60da3a44fc
86b91c07c613f3fdb480701687981e9e18748dc6e918cb2c4c345812da5b
24c5d2536efe766612aa462d8db5c1816297a1dd891273d3acca176f9d97
7f6cb20c3fc896d0e2a72e55b0cbb09afed170cb0dec81986cf8c0ba2dac
738a4482c1f0815ee8ddae0c631b65d5a01fe01d21565d0d17b25f0b4f4f
22389d62631f84b618150667d406829cdbc8e1434a5bb5a7b6524678d0f1
a3f84075d04ffb61e21bbc23b43d5758fdfa29eaf8d2de6342c96bf50a0b
f8f1cf9ca4731d968dee4c36e739840db376eaec9ebdf9cf13af89981c0f
f0e5a95d099f04a4b839c29dd48f7c8df8ab764507e954f6b63b0324db5d
142680f3b15472e4ffdcd5d9d577d64fdbc88a8abce6fcd80ee2cbdcd024
d235a648f44cf6fd09f48bc35f81813bd81d9b538e3f300747e88adb180b
7648092f8c200a28bab9aa507c70ee0172180548c56e869ded7c787fd5d7
9fc95a15d6ecf4e5e200d50f493a428c83d2c58cfc1e966e489f94b47a62
7b7674d01a64a655d5bda02aa78f1d7e936ecd792e0dc14ab4159bb97ddc
7a5258eac809d579ab687668de0158eaea0a54136f8bd3c37cf77dafe0a4
85ecdf5f582a33b7b88c7dad41f16e6a2916a3a2e9957814ed15a249a1b3
c6d6e40218b2fe6053be2f8c4a4cafd59cce0af38369fff531cdbb0a140d
2f936b73fa8966fea082b4ac9f120286aac5ec582f1b18d5c735026469cf
18f62a2d5e0b4967ff8e38e53817a06458fa6069a94f07c591154335d590
7325ae86bba49f0805ad0c94865e0c512bb0e37f8de4825e2ad1062fc2b9
d8c781a806310f6c4bc8e1fddfef0a7748dc716be33a617efbbacc4f8430
b8542123a85fb2fd648b17cafc0016a6614aa04ec7fc3760cfe79000ef34
c32bd532846827d106ccb59ea831f5c094225ca12d9f90668387637c0e00
4ad4c94456f60a970dd1e04f0136fc2c7eb55e31277f5e1619250856d8c3
8d3d21015d35f92457e5ea6e9e06ef8c536b567107a243dd9d34d583e73e
6671a996bafac9ab622379aed51d307b6ff912739f93ecf2ca9a67f3c11d
01d97b8d82cbc32e37e5d12305bb78d6a16b17aaf0d23f809859049604d4
fb8004c5eca2efe249c98177983dc7264d347ba703b3bd5c5da2bce9a36b
48beaef311556b3dd84fbb10620135153864dafe6c62d84383942c2f092b
903f0646d674d08d189efa11dbea753f69abbfa1355ea07a7ec1bca560b9
94965bf83a57605068afc51075cc552bd4178bf5e18a60c48f7665b2d236
a813d44b25eb1e542bcfc5503c862b17d8c5f6a3b44f496639acfa7b671a
c3ea810f47a2a3ea4d6292142a35f8abc7999af114371a46ddcf
```

**Comment by bgrozev** [comment]
This doesn't look like an RTCP packet: the "version" field in the very first two bits is 0 instead of the 2 that RTP/RTCP use. Perhaps there's some encapsulation left, e.g. it contains the UDP headers?

**Comment by gpolitis** [comment]
ditto what @bgrozev said. I just want to add that we have test cases for the TCC packets (RTCPTCCPacketTest.java), @vi do you think you could extract the FCI from the packet you just sent and craft a test case that would demonstrate the issue?

**Comment by sidorovis** [comment]
As I understand that issue: 
There is video hdr-ext: draft-holmer-rmcat-transport-wide-cc-extensions-01. 
And if you have several conference clients, client "A" will receive different sequence number for each external video stream. 
But client "A" Webrtc thinks that all of them are coming from one side and generates feedback message based on that assumption.
So if client "B" will send 15 and client "C" will send 100000 as sequence number, feedback message will store the gap between 15 and 100000. And jvb will receive that feedback and process that for a pretty long time.

**Comment by bgrozev** [comment]
The transport-cc sequence numbers are independent for the different links. "A" will not see the 15 coming from B, it will see the sequence number chosen by the bridge based on the packets being sent to "A". 
If "A" were to send such feedback anyway, one packet is limited to describing 2^16 packets. We would create a TreeMap with ~65000 elements, then loop through it once, then throw it away. This shouldn't cause "busy waiting", but it is a concern for the performance so we created [a fix](https://github.com/jitsi/libjitsi/pull/401).
On the other side, if a sender sends to us RTP packets with big gaps in the transport-cc sequence numbers we would create quite large feedback packets (since we don't yet support encoding using RLE, and we encode each lost packet with its own 2 bit symbol). The PR linked above also avoids that scenario, although it shouldn't cause any real problems.

I still don't understand how the busy waiting condition occurs, and would be interested to see a packet which triggers it.
