### ISSUE TITLE
No video/audio when there are more than 2 users

### ISSUE THREAD

**Issue by jersobh** [jitsi/jitsi-videobridge#574]
Everybody is muted and no video when there are more than two users (p2p mode, I guess). It's an AWS EC2 Ubuntu server, and I've tried stable, testing and nightly builds, none worked. My ssl cert/key where generated by letsencrypt (I'm also using them on prosody).

JICOFO logs:

Jicofo 2017-11-27 12:14:56.704 ADVERTÊNCIA: [95903] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:312)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1846)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1655)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:260)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1086)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1020)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:798)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:150)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1055)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:343)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:226)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1825)
	... 16 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 22 more

jvb.log:

JVB 2017-11-27 12:13:20.783 DETALHADO: [27] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48009" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:30.783 DETALHADO: [29] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48011): <iq id="YWP71-48011" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:30.783 DETALHADO: [29] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48011" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:40.783 DETALHADO: [31] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48013): <iq id="YWP71-48013" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:40.783 DETALHADO: [31] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48013" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:50.784 DETALHADO: [33] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48015): <iq id="YWP71-48015" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:13:50.784 DETALHADO: [33] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48015" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:00.784 DETALHADO: [35] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48017): <iq id="YWP71-48017" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:00.784 DETALHADO: [35] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48017" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:10.783 DETALHADO: [37] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48019): <iq id="YWP71-48019" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:10.784 DETALHADO: [37] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48019" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:20.784 DETALHADO: [39] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48021): <iq id="YWP71-48021" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:20.784 DETALHADO: [39] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48021" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:30.784 DETALHADO: [41] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48023): <iq id="YWP71-48023" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:30.784 DETALHADO: [41] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48023" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:40.784 DETALHADO: [43] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48025): <iq id="YWP71-48025" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:40.784 DETALHADO: [43] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48025" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:50.784 DETALHADO: [45] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48027): <iq id="YWP71-48027" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:14:50.784 DETALHADO: [45] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48027" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:00.785 DETALHADO: [47] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48029): <iq id="YWP71-48029" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:00.785 DETALHADO: [47] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48029" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:10.785 DETALHADO: [49] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48031): <iq id="YWP71-48031" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:10.785 DETALHADO: [49] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48031" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:20.785 DETALHADO: [51] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48033): <iq id="YWP71-48033" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:20.785 DETALHADO: [51] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48033" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:30.785 DETALHADO: [53] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48035): <iq id="YWP71-48035" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:30.785 DETALHADO: [53] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48035" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:40.785 DETALHADO: [55] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48037): <iq id="YWP71-48037" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:40.785 DETALHADO: [55] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48037" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:50.785 DETALHADO: [57] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId YWP71-48039): <iq id="YWP71-48039" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>
JVB 2017-11-27 12:15:50.785 DETALHADO: [57] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="YWP71-48039" type="result" to="jitsi-videobridge.meet.myvidserver.tk" from="meet.myvidserver.tk"/>

**Comment by damencho** [comment]
How did you install/upgrade the package of jicofo?

**Comment by jersobh** [comment]
Nevermind, it's working now. It was the prosody config that had a self-signed cert, generated during the install.
