### ISSUE TITLE
Error: SEVERE: [18] 278 java.net.ConnectException: Connection refused, host:localhost, port:8347

### ISSUE THREAD

**Issue by CahidTopkaraoglu** [jitsi/jitsi-videobridge#599]
Hi, I install the stable jitsi by following the instructions in [here](https://jitsi.org/downloads/).
`wget -qO - https://download.jitsi.org/jitsi-key.gpg.key && sudo apt-key add -`
`sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"`
`sudo apt-get -y update`
*When I updating, I was getting the PUB_KEY ... error. I fixed this issue from [here](https://danielgibbs.co.uk/2012/06/apt-get-gpg-error/)
`sudo apt-get -y install jitsi-meet`
After these steps, I follow [these ](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md)steps to set up jitsi server.
In the 'Install Jitsi Videobridge' step `(./jvb.sh --host=localhost --domain=rocketchat.jitsi --port=8347 --secret=secretkey&)` I get this error.
`JVB 2018-01-18 16:39:04.255 SEVERE: [18] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused, host:localhost, port:8347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Bağlantı reddedildi (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:174)
	... 12 more
`
I don't know much about these. Can anyone help me?

**Comment by saghul** [comment]
You don't need to combine both installation methods. If you installed the `jitsi-meet` meta-package. You probably already have it running, that's why it fails to be started again.

**Comment by CahidTopkaraoglu** [comment]
I was getting this on localhost:5347
 `<?xml version='1.0'?><stream:stream id='' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:component:accept'><stream:error><not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error></stream:stream>`.
Then this because of that. I'll try again thanks.
