### ISSUE TITLE
error videobridge

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-videobridge#656]
Hi,
I'm trying to use this videoconferencing solution
When I try to use the videocall among 3 or more clients I have the following error:
`JVB 2018-05-09 11:29:44.726 SEVERE: [135] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[IceUdpTransportManager connect thread,5,main] and message was: null
java.lang.NullPointerException
	at net.sf.fmj.media.rtp.RTPSessionMgr.getAllParticipants(RTPSessionMgr.java:1144)
	at net.sf.fmj.media.rtp.RTPSessionMgr.getReceiveStreams(RTPSessionMgr.java:1323)
	at org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.getReceiveStreams(RTPTranslatorImpl.java:761)
	at org.jitsi.impl.neomedia.rtp.StreamRTPManager.getReceiveStreams(StreamRTPManager.java:209)
	at org.jitsi.impl.neomedia.MediaStreamImpl.getReceiveStreams(MediaStreamImpl.java:1901)
	at org.jitsi.impl.neomedia.MediaStreamImpl.startReceiveStreams(MediaStreamImpl.java:3135)
	at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3097)
	at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3024)
	at org.jitsi.videobridge.RtpChannel.maybeStartStream(RtpChannel.java:1074)
	at org.jitsi.videobridge.Channel.transportConnected(Channel.java:948)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jitsi.videobridge.IceUdpTransportManager.onIceConnected(IceUdpTransportManager.java:1751)
	at org.jitsi.videobridge.IceUdpTransportManager.lambda$startConnectivityEstablishment$5(IceUdpTransportManager.java:1956)
	at java.lang.Thread.run(Thread.java:748)`

and the following warnings (A lot of this pair)
`JVB 2018-05-09 11:30:26.734 WARNING: [28] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with dce869cb not ready yet.
JVB 2018-05-09 11:30:26.734 WARNING: [28] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message`

do you have a solution for this?
Thank you very much

**Comment by jitsi-developers** [comment]
Reformatting that stack trace, it reads:
JVB 2018-05-09 11:29:44.726 SEVERE: [135]
util.UtilActivator.uncaughtException().122
An uncaught exception occurred in thread=Thread[IceUdpTransportManager
connect thread,5,main] and message was:
null java.lang.NullPointerException
at
net.sf.fmj.media.rtp.RTPSessionMgr.getAllParticipants(RTPSessionMgr.java:1144)
at
net.sf.fmj.media.rtp.RTPSessionMgr.getReceiveStreams(RTPSessionMgr.java:1323)
at
org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.getReceiveStreams(RTPTranslatorImpl.java:761)
at
org.jitsi.impl.neomedia.rtp.StreamRTPManager.getReceiveStreams(StreamRTPManager.java:209)
at
org.jitsi.impl.neomedia.MediaStreamImpl.getReceiveStreams(MediaStreamImpl.java:1901)
at
org.jitsi.impl.neomedia.MediaStreamImpl.startReceiveStreams(MediaStreamImpl.java:3135)
at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3097)
at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3024)
at org.jitsi.videobridge.RtpChannel.maybeStartStream(RtpChannel.java:1074)
at org.jitsi.videobridge.Channel.transportConnected(Channel.java:948)
at java.lang.Iterable.forEach(Iterable.java:75)
at
org.jitsi.videobridge.IceUdpTransportManager.onIceConnected(IceUdpTransportManager.java:1751)
at
org.jitsi.videobridge.IceUdpTransportManager.lambda$startConnectivityEstablishment$5(IceUdpTransportManager.java:1956)
at java.lang.Thread.run(Thread.java:748)


Martin

**Comment by jitsi-developers** [comment]
Ok solved.
The error was about the host name not resolved.
I put inside /etc/hosts the ip associate to my hostname.
Angelo

Il Mer 9 Mag 2018, 13:55 Martin Bonner <martingreybeard@gmail.com> ha
scritto:

> Reformatting that stack trace, it reads:
> JVB 2018-05-09 11:29:44.726 SEVERE: [135]
> util.UtilActivator.uncaughtException().122
> An uncaught exception occurred in thread=Thread[IceUdpTransportManager
> connect thread,5,main] and message was:
> null java.lang.NullPointerException
> at
> net.sf.fmj.media.rtp.RTPSessionMgr.getAllParticipants(RTPSessionMgr.java:1144)
> at
> net.sf.fmj.media.rtp.RTPSessionMgr.getReceiveStreams(RTPSessionMgr.java:1323)
> at
> org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.getReceiveStreams(RTPTranslatorImpl.java:761)
> at
> org.jitsi.impl.neomedia.rtp.StreamRTPManager.getReceiveStreams(StreamRTPManager.java:209)
> at
> org.jitsi.impl.neomedia.MediaStreamImpl.getReceiveStreams(MediaStreamImpl.java:1901)
> at
> org.jitsi.impl.neomedia.MediaStreamImpl.startReceiveStreams(MediaStreamImpl.java:3135)
> at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3097)
> at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3024)
> at org.jitsi.videobridge.RtpChannel.maybeStartStream(RtpChannel.java:1074)
> at org.jitsi.videobridge.Channel.transportConnected(Channel.java:948)
> at java.lang.Iterable.forEach(Iterable.java:75)
> at
> org.jitsi.videobridge.IceUdpTransportManager.onIceConnected(IceUdpTransportManager.java:1751)
> at
> org.jitsi.videobridge.IceUdpTransportManager.lambda$startConnectivityEstablishment$5(IceUdpTransportManager.java:1956)
> at java.lang.Thread.run(Thread.java:748)
>
>
> Martin
>

**Comment by gpolitis** [comment]
Thanks for reporting back with the solution.
