### ISSUE TITLE
sun.nio.ch.SelChImpl exception in build 445

### ISSUE THREAD

**Issue by fippo** [jitsi/jitsi-videobridge#68]
Using the -445 build I get the following exception:
```
2015-04-07 19:07:24.245 INFO: [25] org.jitsi.videobridge.Videobridge.info() Created conference 7d18e3c5e73fae3e. The total number of conferences is now 1, channels 0, video streams 0.
2015-04-07 19:07:24.248 INFO: [25] org.jitsi.videobridge.Conference.info() Created content audio of conference 7d18e3c5e73fae3e. The total number of conferences is now 1, channels 0, video streams 0.
2015-04-07 19:07:24.681 INFO: [25] org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.addLocalAddresses() Not using link-local address /fe80:0:0:0:be76:4eff:fe10:9e5e%4 for TCP candidates.
2015-04-07 19:07:24.681 INFO: [25] org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.addLocalAddresses() Not using link-local address /fe80:0:0:0:be76:4eff:fe10:9a1c%3 for TCP candidates.
2015-04-07 19:07:24.681 INFO: [25] org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.addLocalAddresses() Not using link-local address /fe80:0:0:0:be76:4eff:fe10:757b%2 for TCP candidates.
2015-04-07 19:07:24.683 SEVERE: [25] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[pool-2-thread-3,5,main] and message was: class org.ice4j.socket.DelegatingServerSocketChannel cannot access its superinterface sun.nio.ch.SelChImpl
java.lang.IllegalAccessError: class org.ice4j.socket.DelegatingServerSocketChannel cannot access its superinterface sun.nio.ch.SelChImpl
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.init(MultiplexingTcpHostHarvester.java:609)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:247)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:217)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:198)
        at org.jitsi.videobridge.IceUdpTransportManager.initializeStaticHarvesters(IceUdpTransportManager.java:1732)
        at org.jitsi.videobridge.IceUdpTransportManager.appendVideobridgeHarvesters(IceUdpTransportManager.java:455)
        at org.jitsi.videobridge.IceUdpTransportManager.createIceAgent(IceUdpTransportManager.java:763)
        at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:335)
        at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:303)
        at org.jitsi.videobridge.Conference.getTransportManager(Conference.java:1139)
        at org.jitsi.videobridge.Channel.initialize(Channel.java:528)
        at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:876)
        at org.jitsi.videobridge.Content.createRtpChannel(Content.java:275)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:733)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:545)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleColibriConferenceIQ(ComponentImpl.java:209)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQRequest(ComponentImpl.java:380)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:311)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:263)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQSet(ComponentImpl.java:437)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
```
-433 still works, happy bisecting

**Comment by bgrozev** [comment]
@fippo What JRE version did you see that on?

**Comment by fippo** [comment]
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by xplicit** [comment]
I've got the same error https://github.com/jitsi/jitsi-meet/issues/280#issuecomment-99957923

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by vi** [comment]
Stopped by the same error.

Tried both OpenJDK and Oracle's java with the same error.

**Comment by emcho** [comment]
You guys should be using Java8

**Comment by vi** [comment]
If so, it should explicitly state so, like "This version of Java is not supported. Use Java version ...".

**Comment by xplicit** [comment]
If java8 is required installation packages should have java8 dependency.

**Comment by lyubomir** [comment]
Guys, it's my bad, I'm terribly sorry. It's not like we decided to require 1.8 now, I merely pushed a feature that turned out to not work on all supported Java runtime versions and I'll be trying to figure out a solution as soon as possible.

**Comment by fippo** [comment]
@lyubomir no worries, that's why feedback is important. Thanks!

**Comment by bgrozev** [comment]
Is this fixed with https://github.com/jitsi/jitsi-videobridge/commit/1cc8e23d9179b3f82e64f4511643b8a1382eebfb ?

**Comment by lyubomir** [comment]
I believe it is fixed, @bgrozev.

**Comment by fippo** [comment]
Yes, build 450 works again. Thanks!
