### ISSUE TITLE
M Install with some questions

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-videobridge#698]
```shell
root@tcpdc:~/jitsi-videobridge-linux-x86-1076# ./jvb.sh --host=localhost --domain=example.com --port=5347 --secret=dylanccccc &
[1] 10020
root@tcpdc:~/jitsi-videobridge-linux-x86-1076# Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jitsi/videobridge/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
^C
[1]+  Exit 1                  ./jvb.sh --host=localhost --domain=example.com --port=5347 --secret=dylanccccc
root@tcpdc:~/jitsi-videobridge-linux-x86-1076# java -version
java version "1.7.0_181"
OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-0ubuntu0.1)
OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)
root@tcpdc:~/jitsi-videobridge-linux-x86-1076#
```

what's wrong ?

**Comment by damencho** [comment]
You need to use java8. 

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by WildDylan** [comment]
Okey, the document write this: >= jdk1.7 please change it .

**Comment by damencho** [comment]
@WildDylan Which document?
